version: "3"

volumes:
  mongodb_data:
    driver: local

services:
  luizalabs_mongodb:
    container_name: mongodb_luizalabs
    image: mongo
    logging:
      driver: none
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017